data:
  train_bs: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - 'data/TalkVid-Core.json'
    # - 'data/hallo3.json'
    # - 'data/hdtf.json'
  flip_rate: 0.5
  sample_rate: 1
  num_frames: 20
  reference_margin: 30
  num_padding_audio_frames: 2
  lip_loss_weight: 100
  audio_embeddings_type: 'global' # {global}
  reference_drop_rate: 0.2
  kps_drop_rate: 0.5

module_training:
  denoising_unet: False
  reference_net: False
  v_kps_guider: False
  audio_projection: True
  motion_module: True

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16' # [fp16, bf16, fp32]
  enable_xformers_memory_efficient_attention: True
  reference_net_gradient_checkpointing: False
  denoising_unet_gradient_checkpointing: True
  max_train_steps: 75001  # 20h:14400, 160h:115200
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-6
  scale_lr: False
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 2000
  validate_before_training: False
  validate_at_first_step: True
  data: False
  insightface_model_path: './model_ckpts/insightface_models/'
  image_height: 512
  image_width: 512
  fps: 24
  context_frames: 24
  context_overlap: 4
  num_inference_steps: 25
  guidance_scale: 3.5
  reference_attention_weight: 0.95
  audio_attention_weight: 1.5
  num_pad_audio_frames: 2
  output_dir: ''

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: 'scaled_linear'
  steps_offset: 1
  clip_sample: false

base_model_path: './pretrained_model/sd-image-variations-diffusers'
vae_model_path: './pretrained_model/sd-vae-ft-mse/'
audio_encoder_path: './pretrained_model/wav2vec2-base-960h/'

reference_net_path: './exp/TalkVid-Core/stage_1/reference_net-40000.pth'
denoising_unet_path: './exp/TalkVid-Core/stage_1/denoising_unet-40000.pth'
denoising_unet_state_dict_type: 'new_attn' # {moore_pretrained, old_attn, new_attn}
motion_module_path: './pretrained_model/animatediff/mm_sd_v15_v2.ckpt'
v_kps_guider_path: './exp/TalkVid-Core/stage_1/v_kps_guider-40000.pth'
audio_projection_path: './exp/TalkVid-Core/stage_1/audio_projection-40000.pth'

train_stage: 'stage_2'
save_all: True

weight_dtype: 'fp16' # [fp16, bf16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
stage1_ckpt_dir:
stage1_ckpt_step: 283494

seed: 42
resume_from_checkpoint: '' # 'latest'
checkpointing_steps: 10000
output_dir: './exp/TalkVid-Core'
